# Global configuration for VQA system

api:
  host: "0.0.0.0"
  port: 8000

vlm:
  model_name: "microsoft/phi-4"
  device: "cpu"

redis:
  host: "localhost"
  port: 6379
  db: 0

logging:
  level: "INFO"
  log_file: "logs/vqa.log"