# Example configuration file for the VQA system
vlm:
  # model_id: microsoft/Phi-4-multimodal-instruct  # (original, not available)
  model_id: Salesforce/blip2-opt-2.7b  # Using BLIP-2 for pipeline testing
  device: cpu
  max_new_tokens: 100
  temperature: 0.7

data:
  raw_dir: data/raw
  processed_dir: data/processed
  synthetic_dir: data/synthetic

api:
  host: 0.0.0.0
  port: 8000

retriever:
  top_k: 3
  sources:
    - wikipedia
    - pubmed
    - local

cache:
  redis_url: redis://localhost:6379/0

training:
  epochs: 3
  batch_size: 8
  learning_rate: 5e-5
  save_steps: 500
  eval_steps: 500

evaluation:
  split: "val"
  metrics:
    - accuracy
  dataset_path: data/vqa/val.json
