version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: "redis:7.2"
    ports:
      - "6379:6379"
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - redis