"""
Pydantic models for API requests and responses.
"""

from pydantic import BaseModel, Field

class VQARequest(BaseModel):
    image_url: str = Field(..., description="URL of the image to analyze (not used in Phase 0)")
    question: str = Field(..., description="Question about the image")

class VQAResponse(BaseModel):
    answer: str = Field(..., description="Answer generated by the VLM")